# Generated by Django 5.0.7 on 2024-07-31 22:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mean_rates_per_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='standard_deviation_rates_per_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='total_rating_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='total_rating_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='weight',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
